### PR TITLE
✨ Add support for Python 3.9 and Python 3.9 Alpine

### LINKED ISSUE #23: Add support for Python3.9
The latest supported version of Python is 3.8, while 3.9 is now stable.

### PR DESCRIPTION
**Pull request by gv-collibris**
Closes #23

### CODE REVIEW

**Comment by albertputrapurnama** [comment]
This looks good, when can we merge this @tiangolo ? Thanks!

**Comment by reinhardtgabor** [comment]
Can this be merged @tiangolo ? Please let us know if you see any problems with it, maybe we can sort it out! Thanks!

**Comment by Coffelius** [comment]
Please, merge it

**Comment by samarth-ramesh** [comment]
@tiangolo , while I hate to be the person to "bump", but please, update.

**Comment by tiangolo** [comment]
Great, thanks for your contribution @gv-collibris! :tada: :coffee:

**Pull request merged**
