### PR TITLE
bump alpine to 3.10 across the board, added py3.8 support

### PR DESCRIPTION
**Pull request by matthdsm**
I hope I got all the references...

Cheers
M

### CODE REVIEW

**Comment by matthdsm** [comment]
While I'm at it, should I bump to python3.8 too?

**Comment by matthdsm** [comment]
@tiangolo, please let me know if something else needs to be done for this.

Thanks
M

**Comment by KingDarBoja** [comment]
LGTM 🚀 But should be good to drop Python 2 support for future releases too, just saying.

**Comment by devrsw** [comment]
We'd love to get newer Alpine support for this image - almost worth bumping to 3.13 on this PR?

**Comment by KingDarBoja** [comment]
I do fear the maintainer is too busy to review and merge the PR :sweat:

**Comment by cricket007** [comment]
👋 @tiangolo

**Comment by tiangolo** [comment]
Thanks for your contribution @matthdsm and for the discussion here everyone! :clap: :cake: 

I recently realized that the whole setup I have was quite complex and required a lot of code repetition, which makes it even more difficult to review PRs.

So I refactored it all to simplify the setup and re-use more config files and code.

Then on top of that, I added support for Python 3.8 and for Alpine 3.11 in separate PRs, so that's available now :tada: :rocket:

**Pull request closed without merging**
